### ISSUE TITLE
Update data with Spring 2023

### ISSUE THREAD

**Issue by VineetMalik14** [eduxstad/boiler-grades#7]
Hi,

I have the grade distribution data for the Spring 2023 semester. I believe your database currently has data up to the Fall 2022 semester. It would be great if the stats on the website can include the last semester's data before this semester begins. Let me know if you would be interested in that and how I can assist you in the process.

**Comment by eduxstad** [comment]
Hi Vineet, please feel free to upload the data here or forward it to me at eduxstad@gmail.com. Thanks so much for getting the data!

**Comment by VineetMalik14** [comment]
I have sent the Excel file containing the data over email.
